[tool.poetry]
name = "posture-productivity"
version = "0.1.0"
description = ""
authors = ["BergAndrew <berga2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.2"
numpy = "^1.26.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
